// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inasskoorffkppbtkenm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluYXNza29vcmZma3BwYnRrZW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzIzNjAsImV4cCI6MjA2NTc0ODM2MH0.agEJOV4A8jsO3zszARzo1DzaB7rCjr26nHQjjRmowxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);